module.exports = [
    // ── EAST BLUE SAGA ────────────────────────────────────────────────────────
    { commits: 1,   saga: "East Blue Saga", arc: "Romance Dawn Arc",   message: "🌊 Luffy sets sail from Foosha Village on a little wooden rowboat. The adventure begins!", art: "milestone1.png" },
    { commits: 2,   saga: "East Blue Saga", arc: "Romance Dawn Arc",   message: "🌀 Luffy gets caught by a whirlpool... Will he survive?", art: "milestone2.png" },
    { commits: 3,   saga: "East Blue Saga", arc: "Romance Dawn Arc",   message: "🛢️ Luffy is rescued by Koby in a wooden barrel, but he's being held captive by the evil pirate Alvida...", art: "milestone3.png" },
    { commits: 4,   saga: "East Blue Saga", arc: "Romance Dawn Arc",   message: "👊 Luffy rescues Koby from Alvida with his Gomu Gomu no Pistol! They set off to look for a new crewmate...", art: "milestone4.png" },
    { commits: 5,   saga: "East Blue Saga", arc: "Shells Town Arc",    message: "⚔️ Luffy and Koby arrive in Shells Town and meet the pirate hunter Roronoa Zoro, who is a marine prisoner.", art: "milestone5.png" },
    { commits: 10,  saga: "East Blue Saga", arc: "Shells Town Arc",    message: "🏴‍☠️ Luffy frees Zoro and they defeat Captain Morgan of the Marines. They continue their journey towards the Grand Line, while Koby stays behind to become a marine.", art: "milestone6.png" },
    { commits: 15,  saga: "East Blue Saga", arc: "Orange Town Arc",    message: "🍊 Luffy and Zoro reach Orange Town, where they meet Nami.", art: "milestone7.png" },
    { commits: 18,  saga: "East Blue Saga", arc: "Orange Town Arc",    message: "🤡 The three of them defeat Buggy the clown and his crew, who were terrorizing the town. They set off on their next adventure!", art: "milestone8.png" },
    { commits: 20,  saga: "East Blue Saga", arc: "Orange Town Arc",    message: "🎴 Bonus flashback! Luffy reminisces about how Pirate Shanks and his crew inspired him to form his own crew at a young age.", art: "milestone9.png" },
    { commits: 25,  saga: "East Blue Saga", arc: "Syrup Village Arc",  message: "🐶 The crew arrives at Syrup Village and meets Usopp, a local liar with a big imagination.", art: "milestone10.png" },
    { commits: 30,  saga: "East Blue Saga", arc: "Syrup Village Arc",  message: "🎯 After successfully defending the town from the Black Cat Pirates, Usopp joins the crew, and the Straw Hats receive their first real ship: the Going Merry!", art: "milestone11.png" },
    { commits: 31,  saga: "East Blue Saga", arc: "Syrup Village Arc",  message: "🎴 Bonus flashback: Zoro recalls his childhood and his promise to Kuina of becoming the world's greatest swordsman.", art: "milestone12.png" },
    { commits: 35,  saga: "East Blue Saga", arc: "Baratie Arc",        message: "🍽️ The crew arrives at the floating restaurant Baratie and meets Sanji, a cook.", art: "milestone13.png" },
    { commits: 40,  saga: "East Blue Saga", arc: "Baratie Arc",        message: "🗺️ Nami suddenly steals the Going Merry and sails away from the crew...", art: "milestone14.png" },
    { commits: 45,  saga: "East Blue Saga", arc: "Baratie Arc",        message: "🦅 Dracule Mihawk appears! Zoro challenges the world's strongest swordsman... and loses.", art: "milestone15.png" },
    { commits: 50,  saga: "East Blue Saga", arc: "Baratie Arc",        message: "👨‍🍳 After defeating Don Krieg, Sanji joins the Straw Hats to pursue his dream of finding the All Blue. Luffy and Sanji leave to go find Nami, while Zoro and Usopp have gone ahead.", art: "milestone16.png" },
    { commits: 51,  saga: "East Blue Saga", arc: "Baratie Arc",        message: "🏴‍☠️ Bonus flashback: Usopp recalls his childhood, looking up to his pirate father and losing his mother.", art: "milestone17.png" },
    { commits: 55,  saga: "East Blue Saga", arc: "Arlong Park Arc",    message: "🦈 The Straw Hats arrive at Cocoyasi Village and discover the truth about Nami's past.", art: "milestone18.png" },
    { commits: 56,  saga: "East Blue Saga", arc: "Arlong Park Arc",    message: "🐈‍⬛ Nami's flashback: Nami remembers the pain of losing her adoptive mother, and her devotion to free her village from the Arlong Pirates.", art: "milestone19.png" },
    { commits: 60,  saga: "East Blue Saga", arc: "Arlong Park Arc",    message: "😭 Nami finally asks Luffy for help. The Straw Hats prepare for battle against Arlong and his fish-men crew.", art: "milestone20.png" },
    { commits: 65,  saga: "East Blue Saga", arc: "Arlong Park Arc",    message: "💥 Luffy defeats Arlong and destroys Arlong Park, freeing Nami's village at last.", art: "milestone21.png" },
    { commits: 70,  saga: "East Blue Saga", arc: "Arlong Park Arc",    message: "🧭 Nami officially joins the Straw Hats as their navigator. The crew sails towards the Grand Line!", art: "milestone22.png" },
    { commits: 71,  saga: "East Blue Saga", arc: "Arlong Park Arc",    message: "🍞 Bonus flashback: Sanji recalls getting stranded at sea with Zeff and learning the value of food.", art: "milestone23.png" },
    { commits: 75,  saga: "East Blue Saga", arc: "Loguetown Arc",      message: "🚬 Captain Smoker corners Luffy in Loguetown, the town where Gold Roger was executed.", art: "milestone24.png" },
    { commits: 80,  saga: "East Blue Saga", arc: "Loguetown Arc",      message: "⚡ A sudden storm throws Loguetown into chaos, allowing the Straw Hats to escape the Marines.", art: "milestone25.png" },
    { commits: 85,  saga: "East Blue Saga", arc: "Reverse Mountain Arc", message: "🌊 The crew reaches Reverse Mountain, the gateway to the Grand Line!", art: "milestone26.png" },
    { commits: 90,  saga: "East Blue Saga", arc: "Reverse Mountain Arc", message: "🏴‍☠️ The Straw Hats enter the Grand Line at last! Their real adventure has finally begun, as they meet a large whale...", art: "milestone27.png" },

    // ── ALABASTA SAGA ─────────────────────────────────────────────────────────
    // Whisky Peak Arc (gap +13 from East Blue)
    { commits: 103, saga: "Alabasta Saga", arc: "Whisky Peak Arc",   message: "🍾 The crew docks at Whisky Peak and is welcomed as heroes... but it's a trap! Baroque Works agents attack in the middle of the celebration.", art: "placeholder.png" },
    { commits: 106, saga: "Alabasta Saga", arc: "Whisky Peak Arc",   message: "⚔️ Zoro vs. a hundred Baroque Works agents — then vs. Luffy! Miss All Sunday (Nico Robin) appears and reveals that Vivi is the Princess of Alabasta.", art: "placeholder.png" },
    { commits: 109, saga: "Alabasta Saga", arc: "Whisky Peak Arc",   message: "🔎 Mr. 0 is revealed to be the Warlord Crocodile. The crew's new mission: escort Princess Vivi safely back to Alabasta.", art: "placeholder.png" },
    // Little Garden Arc (gap +5)
    { commits: 114, saga: "Alabasta Saga", arc: "Little Garden Arc", message: "🦕 Little Garden: a prehistoric island frozen in time. Two giants, Dorry and Brogy, have been dueling for 100 years over a misunderstanding of honor.", art: "placeholder.png" },
    { commits: 117, saga: "Alabasta Saga", arc: "Little Garden Arc", message: "🕯️ Mr. 3 and Miss Goldenweek spring a wax trap to kill the giants and the crew. Sanji calls for help from a Den Den Mushi.", art: "placeholder.png" },
    { commits: 120, saga: "Alabasta Saga", arc: "Little Garden Arc", message: "🌋 Giants Dorry and Brogy help the crew escape. Their friendship and honor move even Zoro to silence.", art: "placeholder.png" },
    { commits: 123, saga: "Alabasta Saga", arc: "Little Garden Arc", message: "🧭 The crew escapes Little Garden — but Nami is gravely ill. They need a doctor, fast.", art: "placeholder.png" },
    // Drum Island Arc (gap +5)
    { commits: 128, saga: "Alabasta Saga", arc: "Drum Island Arc",   message: "❄️ Drum Island: a blizzard-covered kingdom abandoned by its ruler. The only doctor left is Kureha, atop the frozen Drum Castle.", art: "placeholder.png" },
    { commits: 131, saga: "Alabasta Saga", arc: "Drum Island Arc",   message: "🏔️ Luffy and Sanji carry Nami up the icy mountain. Luffy holds her in his arms the entire climb without complaint.", art: "placeholder.png" },
    { commits: 134, saga: "Alabasta Saga", arc: "Drum Island Arc",   message: "🎴 Chopper's flashback: Dr. Hiluluk adopted the reindeer shunned by all and lived believing a broken heart can be healed with a smile.", art: "placeholder.png" },
    { commits: 137, saga: "Alabasta Saga", arc: "Drum Island Arc",   message: "🌸 Dr. Hiluluk dies smiling. His final act: making cherry blossoms bloom across the snow of Drum Island.", art: "placeholder.png" },
    { commits: 140, saga: "Alabasta Saga", arc: "Drum Island Arc",   message: "🏳️ The cowardly King Wapol returns. Kureha reveals everything to Chopper: Hiluluk believed in him. His dream can still live.", art: "placeholder.png" },
    { commits: 143, saga: "Alabasta Saga", arc: "Drum Island Arc",   message: "🦌 Tony Tony Chopper joins the crew as their doctor! His dream: to cure any illness in the world.", art: "placeholder.png" },
    // Alabasta Arc (gap +5)
    { commits: 148, saga: "Alabasta Saga", arc: "Alabasta Arc",      message: "🏜️ Alabasta! The crew lands at Nanohana. The air is dry and the country is at war. Smoker is already on their trail.", art: "placeholder.png" },
    { commits: 151, saga: "Alabasta Saga", arc: "Alabasta Arc",      message: "🔥 Luffy runs into his sworn brother Portgas D. Ace in Alabasta — a brief but electrifying reunion.", art: "placeholder.png" },
    { commits: 154, saga: "Alabasta Saga", arc: "Alabasta Arc",      message: "🌵 The crew crosses the desert toward Alubarna. The drought is Crocodile's doing — his Dancing Powder is poisoning the land.", art: "placeholder.png" },
    { commits: 157, saga: "Alabasta Saga", arc: "Alabasta Arc",      message: "🦅 Pell, Alabasta's winged guardian, escorts the crew. His loyalty to the kingdom is absolute.", art: "placeholder.png" },
    { commits: 160, saga: "Alabasta Saga", arc: "Alabasta Arc",      message: "🐊 Crocodile is unmasked as Mr. 0. His plan: ignite civil war and claim the ancient weapon Pluton buried beneath Alabasta.", art: "placeholder.png" },
    { commits: 163, saga: "Alabasta Saga", arc: "Alabasta Arc",      message: "🏛️ The crew splits up. Each member faces a Baroque Works officer to clear the path to Luffy's final showdown.", art: "placeholder.png" },
    { commits: 166, saga: "Alabasta Saga", arc: "Alabasta Arc",      message: "☠️ Luffy vs. Crocodile — Round 1. Crocodile poisons Luffy and drops him into a pit of quicksand. It seems like the end.", art: "placeholder.png" },
    { commits: 169, saga: "Alabasta Saga", arc: "Alabasta Arc",      message: "🩸 Luffy vs. Crocodile — Round 2. Blood neutralizes sand. Luffy fights through poison without stopping.", art: "placeholder.png" },
    { commits: 172, saga: "Alabasta Saga", arc: "Alabasta Arc",      message: "💧 LUFFY DEFEATS CROCODILE! Rain falls on Alabasta for the first time in years. The kingdom is saved.", art: "placeholder.png" },
    { commits: 175, saga: "Alabasta Saga", arc: "Alabasta Arc",      message: "💣 Pell carries the bomb out of the city and detonates it in the sky, sacrificing himself. Alabasta survives.", art: "placeholder.png" },
    { commits: 178, saga: "Alabasta Saga", arc: "Alabasta Arc",      message: "🤝 The armies stop fighting. Vivi appears before her people. The civil war is over.", art: "placeholder.png" },
    { commits: 181, saga: "Alabasta Saga", arc: "Alabasta Arc",      message: "🕊️ Robin saves Vivi from Crocodile's last strike — a mysterious act that hints at her hidden past.", art: "placeholder.png" },
    { commits: 184, saga: "Alabasta Saga", arc: "Alabasta Arc",      message: "🚑 The crew recovers. Marines close in. The group flees through Alabasta's underground tombs.", art: "placeholder.png" },
    { commits: 187, saga: "Alabasta Saga", arc: "Alabasta Arc",      message: "🎀 Farewell to Vivi on the deck of the Going Merry. She weeps, wanting to come — but her duty is to stay. The crew's silence says everything.", art: "placeholder.png" },
    { commits: 190, saga: "Alabasta Saga", arc: "Alabasta Arc",      message: "🌹 Nico Robin boards the ship quietly. \"May I join you?\" — The last words of the arc. She is a Straw Hat.", art: "placeholder.png" },

    // ── SKY ISLAND SAGA ───────────────────────────────────────────────────────
    // Jaya Arc (gap +13)
    { commits: 203, saga: "Sky Island Saga", arc: "Jaya Arc",    message: "🗺️ Jaya — Mock Town. A port of brutal pirates. Luffy and Zoro are mocked by Bellamy, the pirate of the new age.", art: "placeholder.png" },
    { commits: 206, saga: "Sky Island Saga", arc: "Jaya Arc",    message: "🤣 \"There are no more dreams\" — Bellamy humiliates Luffy in front of everyone. Luffy doesn't respond. His eyes say everything.", art: "placeholder.png" },
    { commits: 209, saga: "Sky Island Saga", arc: "Jaya Arc",    message: "👊 Luffy takes down Bellamy in a single punch to defend the honor of Montblanc Cricket. End of story.", art: "placeholder.png" },
    { commits: 212, saga: "Sky Island Saga", arc: "Jaya Arc",    message: "🌊 Montblanc Cricket, heir to the \"liar\" Noland, prepares the crew for the Knock-Up Stream. Skypiea is real.", art: "placeholder.png" },
    { commits: 215, saga: "Sky Island Saga", arc: "Jaya Arc",    message: "⬆️ The Knock-Up Stream! A colossal underwater geyser launches the Going Merry straight into the sky in seconds.", art: "placeholder.png" },
    // Skypiea Arc (gap +5)
    { commits: 220, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "☁️ Skypiea — an island in the clouds, white and silent. The sky is a world of its own. But the crew is not welcome.", art: "placeholder.png" },
    { commits: 223, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "⚖️ The Skypieans speak of \"tribute\" and Enel, their absolute God. Those who disobey are struck by lightning.", art: "placeholder.png" },
    { commits: 226, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "🗿 Upper Yard: ruins of Shandora, the golden city buried in the clouds 400 years ago. Robin senses the Poneglyph's call.", art: "placeholder.png" },
    { commits: 229, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "⚡ Enel reveals his Mantra: he can hear every thought and heartbeat across all of Skypiea.", art: "placeholder.png" },
    { commits: 232, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "🎴 Flashback: the story of Noland and King Calgara. 400 years ago, two friends parted without getting to say goodbye.", art: "placeholder.png" },
    { commits: 235, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "🔔 Dorry and Brogy once heard the bell of Shandora. They have been waiting for it ever since. It hasn't rung in 400 years.", art: "placeholder.png" },
    { commits: 238, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "🏹 The Shandians attack Upper Yard to reclaim their ancestral land. The war in the sky ignites.", art: "placeholder.png" },
    { commits: 241, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "🎭 Enel's game: he eliminates fighters one by one with lightning, toying with their lives as if it were sport.", art: "placeholder.png" },
    { commits: 244, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "🌪️ Enel reveals Plan Raigo: destroy all of Skypiea with a colossal lightning bolt and leave with his followers.", art: "placeholder.png" },
    { commits: 247, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "🛡️ Gan Fall, the former God of Skypiea, fights to protect his people. Zoro and Robin try to hold back the inevitable.", art: "placeholder.png" },
    { commits: 250, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "🦠 Luffy vs. Enel — Round 1! Enel's lightning is useless against Luffy's rubber body. Enel is stunned.", art: "placeholder.png" },
    { commits: 253, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "🐍 Enel transforms his staff into a golden serpent and uses cunning to ground Luffy. But Luffy doesn't stop.", art: "placeholder.png" },
    { commits: 256, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "⚓ Luffy is trapped inside molten gold. Nami faces Enel alone while the great bell looms ahead.", art: "placeholder.png" },
    { commits: 259, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "✊ Luffy breaks free from the gold block, becoming a living hammer. The impact with Enel is devastating.", art: "placeholder.png" },
    { commits: 262, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "🔔 LUFFY DEFEATS ENEL! The Golden Bell of Shandora rings for the first time in 400 years. The whole world hears it. Noland was right.", art: "placeholder.png" },
    { commits: 265, saga: "Sky Island Saga", arc: "Skypiea Arc", message: "🏅 The crew descends back to the Blue Sea loaded with gold. The Shandians and Skypieans make peace. The sky can smile again.", art: "placeholder.png" },

    // ── WATER 7 SAGA ──────────────────────────────────────────────────────────
    // Long Ring Long Land Arc (gap +13)
    { commits: 278, saga: "Water 7 Saga", arc: "Long Ring Long Land Arc", message: "🦊 Long Ring Long Land — a bizarre archipelago. Foxy the Silver Fox challenges the crew to the Davy Back Fight: losers hand over a crewmate.", art: "placeholder.png" },
    { commits: 281, saga: "Water 7 Saga", arc: "Long Ring Long Land Arc", message: "🎪 The Davy Back Fight is full of cheating. Foxy steals Chopper. Luffy fights to win him back.", art: "placeholder.png" },
    { commits: 284, saga: "Water 7 Saga", arc: "Long Ring Long Land Arc", message: "👊 Luffy defeats Foxy! The crew is whole again — but something far more dangerous approaches.", art: "placeholder.png" },
    { commits: 287, saga: "Water 7 Saga", arc: "Long Ring Long Land Arc", message: "🧊 Admiral Aokiji freezes the entire ocean around them. Robin freezes in fear — she knows him. He is from the era of Ohara.", art: "placeholder.png" },
    { commits: 290, saga: "Water 7 Saga", arc: "Long Ring Long Land Arc", message: "😔 Aokiji defeats the entire crew in seconds and lets Luffy go with a warning: Robin will only bring misfortune.", art: "placeholder.png" },
    // Water 7 Arc (gap +5)
    { commits: 295, saga: "Water 7 Saga", arc: "Water 7 Arc", message: "🚢 Water 7 — the city of water. Canals, bridges, shipyards. The Going Merry is in desperate need of repairs.", art: "placeholder.png" },
    { commits: 298, saga: "Water 7 Saga", arc: "Water 7 Arc", message: "🔨 The master shipwrights of Galley-La examine the Going Merry. The verdict: she is beyond repair. The ship is dying.", art: "placeholder.png" },
    { commits: 301, saga: "Water 7 Saga", arc: "Water 7 Arc", message: "💰 The Franky Family robs the crew's repair money. Luffy and the others chase them through the water city streets.", art: "placeholder.png" },
    { commits: 304, saga: "Water 7 Saga", arc: "Water 7 Arc", message: "🕵️ Robin disappears without a word. A coded message: \"Don't come looking for me.\" The crew is torn apart.", art: "placeholder.png" },
    { commits: 307, saga: "Water 7 Saga", arc: "Water 7 Arc", message: "😤 Usopp leaves the crew after a brutal argument with Luffy over the Going Merry. The most painful break of the journey.", art: "placeholder.png" },
    { commits: 310, saga: "Water 7 Saga", arc: "Water 7 Arc", message: "🚨 Head shipwright Iceberg is found nearly dead. Robin is accused. CP9 lurks in the shadows.", art: "placeholder.png" },
    { commits: 313, saga: "Water 7 Saga", arc: "Water 7 Arc", message: "🏗️ The crew kidnaps Franky as leverage. He builds ships — and he is the key to understanding who is behind everything.", art: "placeholder.png" },
    { commits: 316, saga: "Water 7 Saga", arc: "Water 7 Arc", message: "🤫 CP9 unmasked! Kaku and Califa are World Government assassins — they have been infiltrating Water 7 for years.", art: "placeholder.png" },
    { commits: 319, saga: "Water 7 Saga", arc: "Water 7 Arc", message: "📜 The truth about Robin: she is the only survivor of Ohara. The Government has wanted her dead since she was 8 years old.", art: "placeholder.png" },
    { commits: 322, saga: "Water 7 Saga", arc: "Water 7 Arc", message: "🚂 Robin boards the Puffing Tom toward Enies Lobby. The crew mounts the Sea Train and chases her through rain and darkness.", art: "placeholder.png" },
    { commits: 325, saga: "Water 7 Saga", arc: "Water 7 Arc", message: "⚔️ On the train, Sanji fights Blueno of CP9. The first taste of the Six Powers (Rokushiki).", art: "placeholder.png" },
    { commits: 328, saga: "Water 7 Saga", arc: "Water 7 Arc", message: "🌊 The Sea Train flies over the night ocean. Franky joins the crew. Usopp rides in disguise.", art: "placeholder.png" },
    { commits: 331, saga: "Water 7 Saga", arc: "Water 7 Arc", message: "🏝️ Enies Lobby on the horizon — the World Government's judicial fortress. Impossible to storm. The crew will try anyway.", art: "placeholder.png" },
    // Enies Lobby Arc (gap +5)
    { commits: 336, saga: "Water 7 Saga", arc: "Enies Lobby Arc", message: "⚔️ The assault on Enies Lobby begins! Straw Hats and Franky Family against ten thousand soldiers and CP9.", art: "placeholder.png" },
    { commits: 339, saga: "Water 7 Saga", arc: "Enies Lobby Arc", message: "🔥 Luffy orders the World Government flag burned. Open war is declared. No one has ever dared this much.", art: "placeholder.png" },
    { commits: 342, saga: "Water 7 Saga", arc: "Enies Lobby Arc", message: "📚 Robin's past: the destruction of Ohara. Marines burned the library and massacred the scholars. Robin was a child — the only survivor.", art: "placeholder.png" },
    { commits: 345, saga: "Water 7 Saga", arc: "Enies Lobby Arc", message: "😭 \"I WANT TO LIVE!\" Robin screams for the first time in her life. Every wall comes down.", art: "placeholder.png" },
    { commits: 348, saga: "Water 7 Saga", arc: "Enies Lobby Arc", message: "🌊 Luffy activates Gear Second for the first time against Blueno. Speed and power doubled.", art: "placeholder.png" },
    { commits: 351, saga: "Water 7 Saga", arc: "Enies Lobby Arc", message: "⚡ Zoro vs. Kaku — twin swords against a giraffe-Zoan. Asura: the nine-sword demon.", art: "placeholder.png" },
    { commits: 354, saga: "Water 7 Saga", arc: "Enies Lobby Arc", message: "🍂 Sanji vs. Jabra — fire kicks against wolf fangs. \"Diable Jambe!\" scorches Jabra from the inside.", art: "placeholder.png" },
    { commits: 357, saga: "Water 7 Saga", arc: "Enies Lobby Arc", message: "🎯 Usopp in disguise as \"Sniper King\" rallies the fighters and pulls Robin back from the Buster Call.", art: "placeholder.png" },
    { commits: 360, saga: "Water 7 Saga", arc: "Enies Lobby Arc", message: "🏛️ The Buster Call is activated. Six Marine warships surround Enies Lobby. The countdown begins.", art: "placeholder.png" },
    { commits: 363, saga: "Water 7 Saga", arc: "Enies Lobby Arc", message: "💪 Luffy vs. Rob Lucci — the hardest fight of his life. Gear Second and Gear Third combined. Lucci is unstoppable.", art: "placeholder.png" },
    { commits: 366, saga: "Water 7 Saga", arc: "Enies Lobby Arc", message: "😔 Luffy is down. Usopp, as Sniper King, calls out to him: \"Get up! You can't lose!\" Luffy stands.", art: "placeholder.png" },
    { commits: 369, saga: "Water 7 Saga", arc: "Enies Lobby Arc", message: "🏆 LUFFY DEFEATS ROB LUCCI! The Marine Buster Call closes in. Robin is free.", art: "placeholder.png" },
    { commits: 372, saga: "Water 7 Saga", arc: "Enies Lobby Arc", message: "⛵ The Going Merry appears out of nowhere to rescue the crew from the Buster Call. The ship's voice answers her captain.", art: "placeholder.png" },
    { commits: 375, saga: "Water 7 Saga", arc: "Enies Lobby Arc", message: "💧 Out of danger, the Going Merry breaks apart. The crew mourns her as she sinks — a Viking funeral at sea.", art: "placeholder.png" },
    // Post-Enies Lobby Arc (gap +5)
    { commits: 380, saga: "Water 7 Saga", arc: "Post-Enies Lobby Arc", message: "🤝 Usopp apologizes before the whole crew. It takes more courage than it looks. He is welcomed back with open arms.", art: "placeholder.png" },
    { commits: 383, saga: "Water 7 Saga", arc: "Post-Enies Lobby Arc", message: "🎉 Robin and Franky officially join the Straw Hats. Nine crew members now sail together.", art: "placeholder.png" },
    { commits: 386, saga: "Water 7 Saga", arc: "Post-Enies Lobby Arc", message: "☀️ The Thousand Sunny is launched! Franky's masterpiece, built from Adam Wood. The crew's new home.", art: "placeholder.png" },

    // ── THRILLER BARK SAGA ────────────────────────────────────────────────────
    // (gap +13)
    { commits: 399, saga: "Thriller Bark Saga", arc: "Thriller Bark Arc", message: "🌫️ The Florian Triangle: eternal fog, no moon. Ships vanish, distant screams. The Thousand Sunny cannot break free.", art: "placeholder.png" },
    { commits: 402, saga: "Thriller Bark Saga", arc: "Thriller Bark Arc", message: "💀 Thriller Bark — a massive ship-island. Zombies everywhere. The master is Gecko Moria, Warlord of the Sea.", art: "placeholder.png" },
    { commits: 405, saga: "Thriller Bark Saga", arc: "Thriller Bark Arc", message: "🎻 Brook! A living skeleton who plays the violin. He ate the Yomi Yomi no Mi — he died once and waits to see his shadow again.", art: "placeholder.png" },
    { commits: 408, saga: "Thriller Bark Saga", arc: "Thriller Bark Arc", message: "🎴 Brook's flashback: his crew died of illness, and he waited alone for years among the corpses. His grief is silent and immense.", art: "placeholder.png" },
    { commits: 411, saga: "Thriller Bark Saga", arc: "Thriller Bark Arc", message: "🌑 Gecko Moria uses the Kage Kage no Mi to steal everyone's shadows. Without a shadow, the crew dies in sunlight.", art: "placeholder.png" },
    { commits: 414, saga: "Thriller Bark Saga", arc: "Thriller Bark Arc", message: "👾 Luffy's shadow is placed inside the gigantic corpse Oz — a colossus that mimics all of Luffy's moves.", art: "placeholder.png" },
    { commits: 417, saga: "Thriller Bark Saga", arc: "Thriller Bark Arc", message: "🔮 Perona's Negative Hollows demoralize the entire crew. Only Usopp is immune — because he is already negative.", art: "placeholder.png" },
    { commits: 420, saga: "Thriller Bark Saga", arc: "Thriller Bark Arc", message: "🏹 The crew reclaims shadows one by one, defeating each zombie. Oz is the final obstacle.", art: "placeholder.png" },
    { commits: 423, saga: "Thriller Bark Saga", arc: "Thriller Bark Arc", message: "💪 Nightmare Luffy — with 100 shadows inside his body, Luffy becomes a black giant and fires a Gum-Gum Pistol alone.", art: "placeholder.png" },
    { commits: 426, saga: "Thriller Bark Saga", arc: "Thriller Bark Arc", message: "👊 LUFFY DEFEATS GECKO MORIA! The shadows return to their rightful owners. Thriller Bark's dawn is safe.", art: "placeholder.png" },
    { commits: 429, saga: "Thriller Bark Saga", arc: "Thriller Bark Arc", message: "🤺 Bartholomew Kuma arrives on behalf of the Government. Zoro offers to die in Luffy's place. Nothing happened, right?", art: "placeholder.png" },
    { commits: 432, saga: "Thriller Bark Saga", arc: "Thriller Bark Arc", message: "🎵 Brook joins the Straw Hats as musician! His dream: to return to the giant whale Laboon who is still waiting.", art: "placeholder.png" },

    // ── SUMMIT WAR SAGA ───────────────────────────────────────────────────────
    // Sabaody Archipelago Arc (gap +13)
    { commits: 445, saga: "Summit War Saga", arc: "Sabaody Archipelago Arc", message: "🏝️ Sabaody Archipelago — the bubble archipelago near the Red Line. The Eleven Supernovas cross paths for the first time.", art: "placeholder.png" },
    { commits: 448, saga: "Summit War Saga", arc: "Sabaody Archipelago Arc", message: "⚓ The Supernovas: Law, Kid, Hawkins, Drake, Apoo, Bonney, Urouge, Bege, Killer. All headed to the Grand Line.", art: "placeholder.png" },
    { commits: 451, saga: "Summit War Saga", arc: "Sabaody Archipelago Arc", message: "☠️ At a slave auction, Luffy sees a Fish-Man for sale — and punches a Celestial Dragon without hesitation.", art: "placeholder.png" },
    { commits: 454, saga: "Summit War Saga", arc: "Sabaody Archipelago Arc", message: "🚨 Admiral Kizaru arrives. The Pacifista attacks. Rayleigh, the Dark King, appears to cover the retreat.", art: "placeholder.png" },
    { commits: 457, saga: "Summit War Saga", arc: "Sabaody Archipelago Arc", message: "💨 Bartholomew Kuma scatters the entire crew using his paw powers. One by one, they vanish in seconds.", art: "placeholder.png" },
    { commits: 460, saga: "Summit War Saga", arc: "Sabaody Archipelago Arc", message: "😔 Luffy is alone at Sabaody. No crewmates. For the first time in his life, he feels powerless.", art: "placeholder.png" },
    // Amazon Lily Arc (gap +5)
    { commits: 465, saga: "Summit War Saga", arc: "Amazon Lily Arc", message: "👑 Amazon Lily — an island of warrior women. Luffy crashes in by accident. Empress Boa Hancock sentences him to death.", art: "placeholder.png" },
    { commits: 468, saga: "Summit War Saga", arc: "Amazon Lily Arc", message: "💪 Luffy is immune to Hancock's powers — he's not attracted to her, he's just worried about his crew. Hancock is baffled.", art: "placeholder.png" },
    { commits: 471, saga: "Summit War Saga", arc: "Amazon Lily Arc", message: "⛓️ Luffy learns Ace will be executed at Marineford. Hancock helps him. Next stop: Impel Down.", art: "placeholder.png" },
    // Impel Down Arc (gap +5)
    { commits: 476, saga: "Summit War Saga", arc: "Impel Down Arc", message: "🏴 Impel Down — the world's most secure underwater prison. Six levels, each a different nightmare. Luffy breaks in illegally.", art: "placeholder.png" },
    { commits: 479, saga: "Summit War Saga", arc: "Impel Down Arc", message: "🌹 Luffy frees Buggy and Mr. 3. Finds Bon Clay on Level 3. Every improvised ally counts.", art: "placeholder.png" },
    { commits: 482, saga: "Summit War Saga", arc: "Impel Down Arc", message: "🔥 Level 4 — the Devil's Flames. Magellan poisons Luffy with the Hydra. Luffy hovers at the edge of death.", art: "placeholder.png" },
    { commits: 485, saga: "Summit War Saga", arc: "Impel Down Arc", message: "💉 Ivankov saves Luffy with hormone therapy. Luffy wakes after 20 hours of agony — with new resistance to poison.", art: "placeholder.png" },
    { commits: 488, saga: "Summit War Saga", arc: "Impel Down Arc", message: "🤝 Luffy frees Jinbe and Crocodile. An impossible alliance for an impossible escape. Ace has already been moved to Marineford.", art: "placeholder.png" },
    { commits: 490, saga: "Summit War Saga", arc: "Impel Down Arc", message: "⚔️ The breakout crew smashes through every level toward the exit. Magellan pursues them. Time is running out.", art: "placeholder.png" },
    // Marineford Arc (gap +5)
    { commits: 495, saga: "Summit War Saga", arc: "Marineford Arc", message: "⚔️ MARINEFORD — The War of the Best erupts. Whitebeard's fleet against the full Marine Headquarters. The world holds its breath.", art: "placeholder.png" },
    { commits: 498, saga: "Summit War Saga", arc: "Marineford Arc", message: "🌊 Whitebeard splits the sea with one hand. The Marines stand motionless before the impossible.", art: "placeholder.png" },
    { commits: 501, saga: "Summit War Saga", arc: "Marineford Arc", message: "🏃 Luffy arrives at Marineford on an improvised raft. The Impel Down escapees charge into the chaos.", art: "placeholder.png" },
    { commits: 504, saga: "Summit War Saga", arc: "Marineford Arc", message: "🔱 Whitebeard is betrayed by Squard. He keeps fighting — for his sons, not for himself.", art: "placeholder.png" },
    { commits: 507, saga: "Summit War Saga", arc: "Marineford Arc", message: "😤 Luffy reaches the scaffold. Ace is freed... one moment of hope. Then Admiral Akainu strikes.", art: "placeholder.png" },
    { commits: 510, saga: "Summit War Saga", arc: "Marineford Arc", message: "💔 ACE DIES shielding Luffy from Akainu's magma fist. Luffy collapses. The void is total.", art: "placeholder.png" },
    { commits: 513, saga: "Summit War Saga", arc: "Marineford Arc", message: "🏴 Whitebeard's final stand. He dies upright with 267 sword wounds and 152 gunshots. \"The One Piece is real!\" He never showed his back.", art: "placeholder.png" },
    { commits: 516, saga: "Summit War Saga", arc: "Marineford Arc", message: "🌅 Shanks and the Red Hair Pirates arrive. The war ends instantly. The era of Whitebeard is over.", art: "placeholder.png" },
    // Post-War Arc (gap +5)
    { commits: 521, saga: "Summit War Saga", arc: "Post-War Arc", message: "😞 Luffy awakens on the island of women. The void left by Ace is unbearable. Jinbe holds him together.", art: "placeholder.png" },
    { commits: 524, saga: "Summit War Saga", arc: "Post-War Arc", message: "🔔 Luffy returns to Marineford with Jinbe. He rings the Ox Bell 16 times — a coded message to his crew: wait two years.", art: "placeholder.png" },
    { commits: 527, saga: "Summit War Saga", arc: "Post-War Arc", message: "📰 The newspapers carry the message. The crew understands. Each one prepares, trains, and waits.", art: "placeholder.png" },
    { commits: 530, saga: "Summit War Saga", arc: "Post-War Arc", message: "⏳ THE 2-YEAR TIME SKIP. The Straw Hats scatter across the world. Luffy trains with Rayleigh on Rusukaina Island. The world changes.", art: "placeholder.png" },

    // ── FISH-MAN ISLAND SAGA ──────────────────────────────────────────────────
    // Return to Sabaody Arc (gap +13)
    { commits: 543, saga: "Fish-Man Island Saga", arc: "Return to Sabaody Arc",  message: "🎉 Two years later — the entire Straw Hat crew reunites at Sabaody. Everyone has changed. Everyone has grown.", art: "placeholder.png" },
    { commits: 546, saga: "Fish-Man Island Saga", arc: "Return to Sabaody Arc",  message: "💪 Luffy defeats a Pacifista with a single punch — where before it took the whole crew. The power gap is unmistakable.", art: "placeholder.png" },
    // Fish-Man Island Arc (gap +5)
    { commits: 551, saga: "Fish-Man Island Saga", arc: "Fish-Man Island Arc",    message: "🌊 The Thousand Sunny dives into the ocean coated in a bubble. Fish-Man Island awaits at 10,000 meters depth.", art: "placeholder.png" },
    { commits: 554, saga: "Fish-Man Island Saga", arc: "Fish-Man Island Arc",    message: "🐙 The Kraken blocks the descent. Luffy defeats it and names it Surume. A giant squid as a pet.", art: "placeholder.png" },
    { commits: 557, saga: "Fish-Man Island Saga", arc: "Fish-Man Island Arc",    message: "🐟 Fish-Man Island — a beautiful underwater kingdom full of light and coral. But tension with humans runs deep.", art: "placeholder.png" },
    { commits: 560, saga: "Fish-Man Island Saga", arc: "Fish-Man Island Arc",    message: "👑 Princess Shirahoshi — the largest creature in the ocean, able to summon Sea Kings. She is Poseidon.", art: "placeholder.png" },
    { commits: 563, saga: "Fish-Man Island Saga", arc: "Fish-Man Island Arc",    message: "☠️ Hody Jones and the New Fish-Man Pirates want to destroy humans and conquer the kingdom. They take Energy Steroids.", art: "placeholder.png" },
    { commits: 566, saga: "Fish-Man Island Saga", arc: "Fish-Man Island Arc",    message: "🗡️ Zoro vs. Hody Jones. Luffy vs. Hody Jones. The post-time-skip crew is on another level entirely.", art: "placeholder.png" },
    { commits: 569, saga: "Fish-Man Island Saga", arc: "Fish-Man Island Arc",    message: "🔥 Luffy uses Red Hawk — a Gear Second fist coated in Armament Haki, blazing even underwater.", art: "placeholder.png" },
    { commits: 572, saga: "Fish-Man Island Saga", arc: "Fish-Man Island Arc",    message: "💊 Hody Jones takes a massive dose of Energy Steroids to survive. His body is consuming itself.", art: "placeholder.png" },
    { commits: 575, saga: "Fish-Man Island Saga", arc: "Fish-Man Island Arc",    message: "🏆 LUFFY DEFEATS HODY JONES! Fish-Man Island is saved. Luffy vows to fight Big Mom, its fearsome protector.", art: "placeholder.png" },
    { commits: 578, saga: "Fish-Man Island Saga", arc: "Fish-Man Island Arc",    message: "🌺 The story of Otohime and her dream of coexistence between humans and fish-men. Fisher Tiger is the forgotten true hero.", art: "placeholder.png" },
    { commits: 581, saga: "Fish-Man Island Saga", arc: "Fish-Man Island Arc",    message: "🌊 The crew leaves Fish-Man Island for the New World. Jinbe stays behind to settle things, promising to join later.", art: "placeholder.png" },

    // ── DRESSROSA SAGA ────────────────────────────────────────────────────────
    // Punk Hazard Arc (gap +13)
    { commits: 594, saga: "Dressrosa Saga", arc: "Punk Hazard Arc",  message: "🔬 Punk Hazard — a forbidden island, half fire and half ice, aftermath of a failed Vegapunk and Caesar experiment.", art: "placeholder.png" },
    { commits: 597, saga: "Dressrosa Saga", arc: "Punk Hazard Arc",  message: "🧪 Caesar Clown experiments on kidnapped children with the Shinokuni gas. A war criminal protected by Doflamingo.", art: "placeholder.png" },
    { commits: 600, saga: "Dressrosa Saga", arc: "Punk Hazard Arc",  message: "🤝 Trafalgar Law proposes a pirate alliance with Luffy. Objective: bring down one of the Emperors — Kaido.", art: "placeholder.png" },
    { commits: 603, saga: "Dressrosa Saga", arc: "Punk Hazard Arc",  message: "🐉 Law swaps the crew's bodies with his Ope Ope no Mi. Total chaos — and a lot of laughs.", art: "placeholder.png" },
    { commits: 606, saga: "Dressrosa Saga", arc: "Punk Hazard Arc",  message: "🏔️ Nami-in-Sanji's body discovers giant children held prisoner. Caesar drugged them to keep control.", art: "placeholder.png" },
    { commits: 609, saga: "Dressrosa Saga", arc: "Punk Hazard Arc",  message: "☠️ Shinokuni gas is released across the island. Anyone touched crystallizes. The race for survival begins.", art: "placeholder.png" },
    { commits: 612, saga: "Dressrosa Saga", arc: "Punk Hazard Arc",  message: "🔗 The great escape: the crew, children, and prisoners must get off Punk Hazard before the gas reaches them.", art: "placeholder.png" },
    { commits: 615, saga: "Dressrosa Saga", arc: "Punk Hazard Arc",  message: "🌬️ Luffy vs. Caesar Clown — Round 1. Caesar is immune to gas. But Luffy uses Haki to strike the body directly.", art: "placeholder.png" },
    { commits: 618, saga: "Dressrosa Saga", arc: "Punk Hazard Arc",  message: "👊 LUFFY DEFEATS CAESAR CLOWN! The SAD factory is destroyed. One of Kaido's key resources is cut off.", art: "placeholder.png" },
    { commits: 621, saga: "Dressrosa Saga", arc: "Punk Hazard Arc",  message: "📜 Vergo, the traitorous Marine, is exposed and defeated by Law. Doflamingo's network inside the government begins to crack.", art: "placeholder.png" },
    { commits: 624, saga: "Dressrosa Saga", arc: "Punk Hazard Arc",  message: "🚢 A grand coalition forms: Straw Hats, Law, samurai of Wano, rescued children. Destination: Dressrosa.", art: "placeholder.png" },
    // Dressrosa Arc (gap +5)
    { commits: 629, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🌸 Dressrosa — a colorful kingdom of passion, flamenco, and gladiators. But the streets are full of living \"toys\".", art: "placeholder.png" },
    { commits: 632, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🏟️ The Corrida Colosseum! A tournament to win Ace's Devil Fruit. Luffy enters as \"Lucy\" wearing a gladiator helmet.", art: "placeholder.png" },
    { commits: 635, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🎲 Donquixote Doflamingo rules Dressrosa from his palace. His true nature: a renegade Celestial Dragon.", art: "placeholder.png" },
    { commits: 638, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🧸 The truth about the toys: they are humans transformed by Sugar's Hobi Hobi no Mi. No one remembers them.", art: "placeholder.png" },
    { commits: 641, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🤡 The SMILE factory: Doflamingo manufactures artificial fruits to turn Kaido's soldiers into Zoan-type weapons.", art: "placeholder.png" },
    { commits: 644, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🔥 Sabo is alive! Ace's brother appears at the Colosseum and eats the Mera Mera no Mi before everyone's eyes.", art: "placeholder.png" },
    { commits: 647, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🎯 Usopp fights Sugar to free the toys. His \"monster\" face terrifies her — the curse breaks. The toys turn human again.", art: "placeholder.png" },
    { commits: 650, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🌟 GOD USOPP! The Tontatta dwarves proclaim him a deity. Usopp cries — he didn't want to fight — but he won.", art: "placeholder.png" },
    { commits: 653, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "⚔️ The toys reclaim their humanity and their memories. Doflamingo's own soldiers turn against him. The palace crumbles.", art: "placeholder.png" },
    { commits: 656, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🕊️ The Birdcage descends on Dressrosa. Invisible, lethal strings slowly closing in. Doflamingo will trap everyone.", art: "placeholder.png" },
    { commits: 659, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "👑 The story of Riku and Violet: how Doflamingo seized power ten years ago, using the kingdom against itself.", art: "placeholder.png" },
    { commits: 662, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🏃 Luffy, Law, and the survivors race toward the palace. Every moment, the Birdcage tightens.", art: "placeholder.png" },
    { commits: 665, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "⚡ Law vs. Doflamingo — Round 1. Law uses \"Mes\" to extract Doflamingo's heart... but he survives.", art: "placeholder.png" },
    { commits: 668, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "💪 GEAR FOURTH — BOUNDMAN! Luffy coats his body in expanded Armament Haki. A transformation that transcends normal.", art: "placeholder.png" },
    { commits: 671, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🤜 Luffy vs. Doflamingo — the reckoning. Gum-Gum King Kong Gun against the web of strings.", art: "placeholder.png" },
    { commits: 674, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🏆 LUFFY DEFEATS DOFLAMINGO! The Birdcage dissolves. Dressrosa is free. Bounty: 500,000,000 Berry.", art: "placeholder.png" },
    { commits: 677, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🌺 The people of Dressrosa chase the crew to arrest them... then stop. Just to thank them. Tears everywhere.", art: "placeholder.png" },
    { commits: 680, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "⚓ The Straw Hat Grand Fleet — seven crews with 5,640 warriors pledge eternal loyalty to Luffy after Dressrosa.", art: "placeholder.png" },
    { commits: 683, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "📜 Rebecca finds her father Kyros. The tin soldier who couldn't embrace his daughter for 10 years can finally hold her.", art: "placeholder.png" },
    { commits: 686, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🦁 Sabo faces Admiral Fujitora to cover the crew's retreat. Another impossible fight that buys precious time.", art: "placeholder.png" },
    { commits: 689, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🚢 The reunited crew leaves Dressrosa. Zou is next — and an even greater war is drawing near.", art: "placeholder.png" },
    { commits: 692, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "📰 The news of Dressrosa spreads across the world. Luffy's name echoes everywhere. Kaido takes notice.", art: "placeholder.png" },
    { commits: 695, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🤝 The Straw Hat–Law alliance is solidified. The strategy against Kaido takes shape — Wano is the final destination.", art: "placeholder.png" },
    { commits: 698, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "🎴 Law's flashback: the kingdom of Flevance and the white disease. Donquixote Rosinante was his anchor. He loved him as a father.", art: "placeholder.png" },
    { commits: 700, saga: "Dressrosa Saga", arc: "Dressrosa Arc",    message: "⚔️ Doflamingo is delivered to the Marines. A Warlord in chains — the political shockwave changes the balance of the world.", art: "placeholder.png" },

    // ── WHOLE CAKE ISLAND SAGA ────────────────────────────────────────────────
    // Zou Arc (gap +13)
    { commits: 713, saga: "Whole Cake Island Saga", arc: "Zou Arc",              message: "🐘 Zou — a living island on the back of Zunesha, a millennial elephant that has walked the ocean for 1,000 years.", art: "placeholder.png" },
    { commits: 716, saga: "Whole Cake Island Saga", arc: "Zou Arc",              message: "🐆 The Minks — half-human, half-animal warriors. Enemies of Kaido's Jack, who devastated the island searching for samurai Raizo.", art: "placeholder.png" },
    { commits: 719, saga: "Whole Cake Island Saga", arc: "Zou Arc",              message: "🗡️ The samurai of Wano: Kin'emon, Kanjuro, Raizo. The Kozuki clan and its connection to the Poneglyphs.", art: "placeholder.png" },
    { commits: 722, saga: "Whole Cake Island Saga", arc: "Zou Arc",              message: "📜 The Road Poneglyphs — four stones scattered across the world. Only those who find all four can chart the route to Laugh Tale.", art: "placeholder.png" },
    { commits: 725, saga: "Whole Cake Island Saga", arc: "Zou Arc",              message: "💌 Sanji's note: he's been forced to return to his biological family, the Vinsmoke family of Germa 66. He doesn't want to be saved.", art: "placeholder.png" },
    { commits: 728, saga: "Whole Cake Island Saga", arc: "Zou Arc",              message: "🐉 Kaido arrives on Zou — no, it's just Jack. But the threat of Kaido as an Emperor is becoming very real.", art: "placeholder.png" },
    // Whole Cake Island Arc (gap +5)
    { commits: 733, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "🍰 Whole Cake Island — Big Mom's territory. An island made of food, sugar houses, chocolate trees. Beautiful and terrifying.", art: "placeholder.png" },
    { commits: 736, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "👻 The Homies — creatures animated by souls stolen by Big Mom's Soru Soru no Mi. Everything on the island is alive and obeys.", art: "placeholder.png" },
    { commits: 739, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "💍 The forced wedding between Sanji and Pudding: Big Mom planned to eliminate the Vinsmoke family during the ceremony.", art: "placeholder.png" },
    { commits: 742, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "🧬 The Vinsmoke story: Germa 66, the nomadic scientific kingdom. Judge genetically enhanced his children — all except Sanji.", art: "placeholder.png" },
    { commits: 745, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "😢 Sanji tells Luffy to leave and strikes him. But his hands are trembling — he doesn't want to do this. Luffy waits, absorbing every blow.", art: "placeholder.png" },
    { commits: 748, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "🍊 Nami wields Zeus — Big Mom's own thundercloud — against Big Mom herself. A moment of total anarchic brilliance.", art: "placeholder.png" },
    { commits: 751, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "👁️ Pudding reveals her third eye and her true intentions. But something in her wavers when she sees Sanji's smile.", art: "placeholder.png" },
    { commits: 754, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "💥 Brook copies the Road Poneglyph inside Big Mom's Castle — alone, at night. Skeleton OP.", art: "placeholder.png" },
    { commits: 757, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "🌹 Pedro sacrifices himself, detonating a bomb to stop Baron Tamago. \"My life is already well spent.\"", art: "placeholder.png" },
    { commits: 760, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "🕐 Luffy vs. Katakuri in the Mirro-World — a mirror dimension. Katakuri sees the future with advanced Observation Haki.", art: "placeholder.png" },
    { commits: 763, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "🔮 Luffy realizes: to beat Katakuri he must also see the future. He begins training in the middle of the fight.", art: "placeholder.png" },
    { commits: 766, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "👁️ Luffy opens his eyes — he can see slightly into the future. For the first time he dodges Katakuri's attacks.", art: "placeholder.png" },
    { commits: 769, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "🤜 LUFFY DEFEATS KATAKURI! He scars Katakuri's cheek — mirroring what Katakuri had done to him. Mutual respect.", art: "placeholder.png" },
    { commits: 772, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "🎂 The wedding ceremony collapses. Big Mom goes on a Yonko Rampage — she must have her wedding cake at any cost.", art: "placeholder.png" },
    { commits: 775, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "🍰 Sanji bakes the wedding cake for Big Mom while the crew escapes. The only weapon against her.", art: "placeholder.png" },
    { commits: 778, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "🚢 A frantic escape — Big Mom chases the Thousand Sunny on Prometheus. Jinbe holds the helm with everything he has.", art: "placeholder.png" },
    { commits: 781, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "🌊 Jinbe officially joins the crew as helmsman! He has been waiting for this moment since Marineford.", art: "placeholder.png" },
    { commits: 784, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "👨‍🍳 Sanji cooks a meal for Luffy who hasn't eaten in days. \"As long as I cook for you, your life belongs to me.\"", art: "placeholder.png" },
    { commits: 787, saga: "Whole Cake Island Saga", arc: "Whole Cake Island Arc", message: "⛵ The crew leaves Big Mom's territory. Sanji is back. All Road Poneglyphs have been copied. Destination: Wano.", art: "placeholder.png" },

    // ── WANO COUNTRY SAGA — 37 MILESTONES (MAX) ──────────────────────────────
    // (gap +13)
    { commits: 800, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🏯 Wano Country — the closed samurai nation. Kaido and Orochi have oppressed the people for twenty years.", art: "placeholder.png" },
    { commits: 803, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🎎 The crew splits and infiltrates: Luffy works in a mine, Nami sells kimonos, Zoro wanders as a ronin.", art: "placeholder.png" },
    { commits: 806, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🍱 Wano has lost its beauty — poisoned rivers, barren land, starving people. Kaido has ruined everything.", art: "placeholder.png" },
    { commits: 809, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🏮 The port of Oihara — heart of the resistance. Samurai loyal to the Kozuki clan organize in secret.", art: "placeholder.png" },
    { commits: 812, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "⛓️ Luffy is captured and thrown into Udon Prison along with hundreds of inmates. Kaido wants to break his will.", art: "placeholder.png" },
    { commits: 815, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "💪 Luffy trains with Hyogoro the Flower — the yakuza boss who knows the true Ryou (Wano's advanced Armament Haki).", art: "placeholder.png" },
    { commits: 818, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🎯 Luffy learns to project Armament Haki outside his body to strike from within. A massive qualitative leap.", art: "placeholder.png" },
    { commits: 821, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🌊 Yamato, Kaido's child, sides with the resistance. They want to be Kozuki Oden and open Wano's borders.", art: "placeholder.png" },
    { commits: 824, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "📜 THE FLASHBACK OF KOZUKI ODEN — the legendary warrior who sailed with Whitebeard, then with Roger.", art: "placeholder.png" },
    { commits: 827, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "⚓ Oden on the Moby Dick with Whitebeard. His energy, charisma, and colossal strength. A very special nakama.", art: "placeholder.png" },
    { commits: 830, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🌎 Oden sails with Roger to Laugh Tale — the final island. Only they two will know the truth about the One Piece and the Void Century.", art: "placeholder.png" },
    { commits: 833, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "😭 Oden returns to Wano — and finds a country transformed by Orochi and Kaido. He sacrifices himself to protect his people.", art: "placeholder.png" },
    { commits: 836, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🔥 Oden's execution: boiled alive for an hour while holding his samurai on his shoulders. He laughed until the end. \"I'll be the first to reach Laugh Tale!\"", art: "placeholder.png" },
    { commits: 839, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "⚔️ The Nine Red Scabbards — the last samurai loyal to Oden — ready themselves for vengeance. Twenty years of waiting end now.", art: "placeholder.png" },
    { commits: 842, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🥷 The Alliance is complete: Straw Hats, Law, samurai, Minks. A thousand warriors ready for the raid on Onigashima.", art: "placeholder.png" },
    { commits: 845, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🌊 The raid on Onigashima begins! A thousand warriors disguised as Beast Pirates board the island under cover of night.", art: "placeholder.png" },
    { commits: 848, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🎭 Onigashima — Kaido's fortress. The crew splits up: each member has a specific objective inside.", art: "placeholder.png" },
    { commits: 851, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🐉 Luffy, Zoro, Law, Kid, Killer reach the rooftop — the ultimate stage against the two Emperors.", art: "placeholder.png" },
    { commits: 854, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "⚡ The rooftop of Onigashima. The Five vs. Kaido and Big Mom. The sky cracks under the force of their clashes.", art: "placeholder.png" },
    { commits: 857, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🌪️ Luffy vs. Kaido — Round 1. Kaido defeats Luffy and hurls him off the rooftop. \"Your Haki is not enough yet.\"", art: "placeholder.png" },
    { commits: 860, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🌊 Luffy wakes among the people of Wano, below Onigashima. He sees their suffering. He understands what he's fighting for.", art: "placeholder.png" },
    { commits: 863, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "💪 Luffy climbs back up — not with rage, but with joy. A smile that no one expected.", art: "placeholder.png" },
    { commits: 866, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🌩️ Luffy vs. Kaido — Round 2. Advanced Ryou shatters dragon scales from the inside. Kaido begins to yield.", art: "placeholder.png" },
    { commits: 869, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🎴 Kaido's flashback: his origins, the Rocks Pirates, God Valley. Why he can't die — and why he doesn't care.", art: "placeholder.png" },
    { commits: 872, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "⚡ Advanced Conqueror's Haki — Luffy and Kaido wrap themselves in black lightning as they fight. The sky turns violet.", art: "placeholder.png" },
    { commits: 875, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "☀️ GEAR FIFTH — THE SUN GOD NIKA! Hito Hito no Mi, Model: Nika. Luffy's true awakening. His power is pure freedom.", art: "placeholder.png" },
    { commits: 878, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "😂 Luffy laughs. The world laughs with him. His body becomes cartoon — absolute freedom. Kaido sees a white giant.", art: "placeholder.png" },
    { commits: 881, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🌋 LUFFY DEFEATS KAIDO! Gum-Gum Bajrang Gun sends Kaido plunging into the magma beneath Wano.", art: "placeholder.png" },
    { commits: 884, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🗡️ Law and Kid defeat Big Mom — sending her into the ocean's depths. Two Emperors fall in a single night.", art: "placeholder.png" },
    { commits: 887, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🌸 The Nine Red Scabbards defeat Orochi for the last time. Wano is free for the first time in twenty years.", art: "placeholder.png" },
    { commits: 890, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🐉 Momonosuke uses his dragon powers to lift Onigashima away from Flower Capital and save the city.", art: "placeholder.png" },
    { commits: 893, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🎉 The festival of Flower Capital — the people celebrate without yet knowing they are free. But they will find out.", art: "placeholder.png" },
    { commits: 896, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "👑 Kozuki Momonosuke opens Wano's borders to the world. A new era begins for the Land of the Samurai.", art: "placeholder.png" },
    { commits: 899, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "📰 The news spreads: Luffy is now an Emperor of the Sea. Bounty: 3,000,000,000 Berry. The world trembles.", art: "placeholder.png" },
    { commits: 902, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🚢 The crew prepares to leave Wano. A new crew, stronger than ever. Shanks is waiting somewhere out there.", art: "placeholder.png" },
    { commits: 905, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "🎴 Flashback: Oden laughed even as he died. \"I'll be the first to reach Laugh Tale.\" Not him — but his straw hat will.", art: "placeholder.png" },
    { commits: 908, saga: "Wano Country Saga", arc: "Wano Country Arc", message: "⚓ The Thousand Sunny leaves Wano toward the Final Saga. The One Piece has never been closer.", art: "placeholder.png" },

    // ── FINAL SAGA — EGGHEAD ARC ──────────────────────────────────────────────
    // (gap +13)
    { commits: 921, saga: "Final Saga", arc: "Egghead Arc", message: "🤖 Egghead Island — the \"island of the future\" of Dr. Vegapunk. Technology 500 years ahead of its time. Giant robots, pure sci-fi.", art: "placeholder.png" },
    { commits: 924, saga: "Final Saga", arc: "Egghead Arc", message: "🧪 The six Vegapunk satellites: Shaka (Good), Lilith (Evil), Edison (Thinker), Pythagoras (Wisdom), Atlas (Violence), York (Greed).", art: "placeholder.png" },
    { commits: 927, saga: "Final Saga", arc: "Egghead Arc", message: "🚗 Bonney is on the island — she's looking for Vegapunk to learn the truth about her father, Bartholomew Kuma.", art: "placeholder.png" },
    { commits: 930, saga: "Final Saga", arc: "Egghead Arc", message: "🤺 The Seraphim — ultimate weapons based on former Warlords but with Lunarian blood — turn against everyone without warning.", art: "placeholder.png" },
    { commits: 933, saga: "Final Saga", arc: "Egghead Arc", message: "🧬 York betrayed Vegapunk to become the sole Celestial Dragon scientist in the world. Betrayal from within.", art: "placeholder.png" },
    { commits: 936, saga: "Final Saga", arc: "Egghead Arc", message: "📡 Vegapunk prepares his final broadcast to the world. He wants to speak the truth before he dies.", art: "placeholder.png" },
    { commits: 939, saga: "Final Saga", arc: "Egghead Arc", message: "🌊 Saturn of the Gorosei arrives physically on Egghead in his Mythical Zoan monster form. One of the world's darkest forces.", art: "placeholder.png" },
    { commits: 942, saga: "Final Saga", arc: "Egghead Arc", message: "⚡ Luffy vs. Kizaru in Gear Fifth — a surreal clash between a ray of light and a rubber cartoon man.", art: "placeholder.png" },
    { commits: 945, saga: "Final Saga", arc: "Egghead Arc", message: "📻 Vegapunk's broadcast reaches every Den Den Mushi in the world. The truth about the Void Century and the Ancient Kingdom.", art: "placeholder.png" },
    { commits: 948, saga: "Final Saga", arc: "Egghead Arc", message: "💀 Vegapunk is killed by Kizaru before finishing the message. But the world has already heard enough.", art: "placeholder.png" },
    { commits: 951, saga: "Final Saga", arc: "Egghead Arc", message: "👹 The Five Elders in monster form besiege Egghead. The Gorosei are not just politicians — they are ancient monsters.", art: "placeholder.png" },
    { commits: 954, saga: "Final Saga", arc: "Egghead Arc", message: "🚢 The crew escapes Egghead with the surviving Vegapunk satellites. Kuma reveals his story to Bonney: he was a good king.", art: "placeholder.png" },
    { commits: 957, saga: "Final Saga", arc: "Egghead Arc", message: "🌊 The world reacts to Vegapunk's broadcast: revolutions, riots, global chaos. The World Government is shaken.", art: "placeholder.png" },
    { commits: 960, saga: "Final Saga", arc: "Egghead Arc", message: "⚓ The story of the Lunarians and the Sun — the same origin as Nika. The thread connecting Joyboy, Luffy, and the history of the world.", art: "placeholder.png" },
    { commits: 963, saga: "Final Saga", arc: "Egghead Arc", message: "📜 The Ancient Kingdom fought the World Government 800 years ago. The truth is staggering. The world will never be the same.", art: "placeholder.png" },
    { commits: 966, saga: "Final Saga", arc: "Egghead Arc", message: "🔮 The Stella satellite survives. She carries all of Vegapunk's knowledge. The crew safeguards the world's greatest secret.", art: "placeholder.png" },
    { commits: 968, saga: "Final Saga", arc: "Egghead Arc", message: "🌅 Egghead is behind them. The crew sails toward Elbaf. The Giants' Island is next. And Shanks is there.", art: "placeholder.png" },

    // ── FINAL SAGA — ELBAF ARC ────────────────────────────────────────────────
    // (gap +13)
    { commits: 981,  saga: "Final Saga", arc: "Elbaf Arc", message: "🏔️ ELBAF — The legendary island of giants, the strongest warriors in the world. Usopp's dream materializes before his eyes.", art: "placeholder.png" },
    { commits: 984,  saga: "Final Saga", arc: "Elbaf Arc", message: "😭 Robin meets Jaguar D. Saul — the giant she thought had died at Ohara. He survived. He had been waiting for her.", art: "placeholder.png" },
    { commits: 987,  saga: "Final Saga", arc: "Elbaf Arc", message: "📚 The Library of Elbaf — the greatest repository of knowledge in the world. Everything the Government tried to erase is here.", art: "placeholder.png" },
    { commits: 990,  saga: "Final Saga", arc: "Elbaf Arc", message: "👑 Prince Loki — the chained prince of Elbaf. A story of prophecy, betrayal, and the boundaries of the island.", art: "placeholder.png" },
    { commits: 993,  saga: "Final Saga", arc: "Elbaf Arc", message: "🔴 Shanks and the Red Hair Pirates appear on Elbaf. His true connection to the island — and to Luffy — is finally revealed.", art: "placeholder.png" },
    { commits: 996,  saga: "Final Saga", arc: "Elbaf Arc", message: "☠️ The Blackbeard Pirates and Cross Guild converge on Elbaf. Every remaining power in the world is gathering here.", art: "placeholder.png" },
    { commits: 999,  saga: "Final Saga", arc: "Elbaf Arc", message: "⚔️ The battles of Elbaf erupt on multiple fronts. Giants fight. Pirates fight. The world is being decided here.", art: "placeholder.png" },
    { commits: 1002, saga: "Final Saga", arc: "Elbaf Arc", message: "📜 The Road Poneglyph of Elbaf is found. The last of the four. With this, the route to Laugh Tale can be charted.", art: "placeholder.png" },
    { commits: 1005, saga: "Final Saga", arc: "Elbaf Arc", message: "🌟 The mysteries of the Void Century converge: who was Joyboy, what the Ancient Kingdom held, what guards the One Piece.", art: "placeholder.png" },
    { commits: 1008, saga: "Final Saga", arc: "Elbaf Arc", message: "🤝 Luffy and Shanks come face to face — for the first time since Luffy was a child.", art: "placeholder.png" },
    { commits: 1011, saga: "Final Saga", arc: "Elbaf Arc", message: "⚓ The final battles of Elbaf conclude. The survivors gather their strength.", art: "placeholder.png" },
    { commits: 1014, saga: "Final Saga", arc: "Elbaf Arc", message: "🌊 The Straw Hats prepare to leave Elbaf. Saul smiles at Robin. The giants wave goodbye.", art: "placeholder.png" },
    { commits: 1017, saga: "Final Saga", arc: "Elbaf Arc", message: "🌅 The route to Laugh Tale is charted. The One Piece is within reach. The final voyage begins. Will of D. — Joyboy's promise to the world.", art: "placeholder.png" },
];
